services:
  softsectatou:
    image: softsectatou
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [ "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000" ]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=server/src/server.py
      - PYTHONUNBUFFERED=1
      # DB connection details for future use by the API
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tatou
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
  db:
    image: mariadb:11.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=tatou
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/tatou.sql:/docker-entrypoint-initdb.d/10-tatou.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root --password=$MARIADB_ROOT_PASSWORD --silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306

volumes:
  db-data:
